osu-wams/dx-server

src/api/user.ts
Depends on #12 
Prevents unnecessary data from being exposed through the user api
=> Explicit user api data

config/custom-environment-variables.ts, config/default.ts, config/test.ts, package.json, src/api/__mocks__/announcements.data.ts, src/api/__tests__/announcements.test.ts, src/api/__tests__/index.test.ts, src/api/__tests__/masquerade.test.ts, src/api/__tests__/user.test.ts, src/api/announcements.ts, src/api/models/__mocks__/user.ts, src/api/models/__tests__/user.test.ts, src/api/models/user.ts, src/api/modules/__tests__/canvas.test.ts, src/api/modules/__tests__/user-account.test.ts, src/api/modules/canvas.ts, src/api/modules/dx.ts, src/api/user.ts, src/auth.ts, src/db/__tests__/index.ts, src/db/index.ts, src/index.ts
Depends on #12 and then #13 
Adds coverage and mocks for missing tests
fixes #DD-455
=> Improving coverage

config/custom-environment-variables.ts, config/default.ts, src/api/models/__tests__/user.test.ts, src/api/models/user.ts, src/db/scripts/create_users_table.ts
=> Namespace dynamodb

src/api/__mocks__/holds.data.ts, src/api/__mocks__/student.data.ts, src/api/__tests__/student.test.ts, src/api/modules/osu.ts, src/api/student.ts
Moves the OSU api integration to a module and calls them from the appropriate routes.
=> DRYs up the osu api integration and routes

package.json, src/api/admin.ts, src/api/alerts.ts, src/api/announcements.ts, src/api/models/user.ts, src/api/modules/canvas.ts, src/api/modules/osu.ts, src/api/modules/user-account.ts, src/api/student.ts, src/auth.ts, src/db/scripts/create_users_table.ts, src/db/scripts/list_tables.ts, src/index.ts, src/logger.ts, yarn.lock
=> uses logger for output

config/custom-environment-variables.ts, config/default.ts, src/api/alerts.ts, src/api/announcements.ts, src/api/events.ts, src/api/information.ts, src/api/models/user.ts, src/api/modules/user-account.ts, src/api/persons.ts, src/api/resources.ts, src/api/student.ts, src/api/util.ts, src/logger.ts, src/tracer.ts
adds log level configuration and tracing to push logs cloudwatch
=> adds timing logs and default log level

src/auth.ts
updates session with newly fetched oauth token and expiration date
=> resets session with new oauth token and expiration

jest.config.js, src/api/__mocks__/student.data.ts, src/api/__tests__/student.test.ts, src/api/modules/osu.ts, src/utils/jestSetup.ts
=> removes faculty osuid from returned data

.github/workflows/build_push.yml
I've created a new dx development stack
=> Change fargate info from my-dev to osu-dx

README.md, src/auth.ts
=> Auth logging

src/api/__tests__/events.test.ts, src/api/modules/localist.ts
fixes https://jira.sig.oregonstate.edu/browse/DD-613
=> adds start date query to localist event api query

support/artillery.tests.yml
fixes https://jira.sig.oregonstate.edu/browse/DD-607
=> adds finance page and additional api endpoints for load testing

README.md, src/api/__tests__/admin.test.ts, src/api/admin.ts, src/api/modules/__mocks__/cache.ts, src/api/modules/cache.ts
fixes https://jira.sig.oregonstate.edu/browse/DD-614
=> exposes an admin function to reset the caches for external API calls

src/index.ts
fixes https://jira.sig.oregonstate.edu/browse/DD-617
=> redirects after setting user to opt out of oauth

src/api/__tests__/resources.test.ts, src/api/modules/dx.ts
fixes https://jira.sig.oregonstate.edu/browse/DD-587
This deployment needs to be coordinated along with the related PR in the DX repository
=> uses category name for resources query

src/api/__mocks__/student.data.ts, src/api/__tests__/student.test.ts, src/api/modules/osu.ts
fixes https://jira.sig.oregonstate.edu/browse/DD-622
=> reworks gpa api to include prioritized gpa data

config/default.ts
updates backend cache duration defaults as per discussions with DW and MH
fixes https://jira.sig.oregonstate.edu/browse/DD-642
=> updates backend cache defaults

src/api/modules/dx.ts
sets proper date value in filtering out expired alerts
fixes https://jira.sig.oregonstate.edu/browse/DD-662
=> fixes bug in filtering expired alerts from DX api

src/api/__mocks__/planner-items.data.ts, src/api/modules/__tests__/canvas.test.ts, src/api/modules/canvas.ts, src/api/student.ts
refactors Canvas API module for clarity and future use of other APIs
=> Canvas api extensions

src/api/__tests__/admin.test.ts, src/api/__tests__/alerts.test.ts, src/api/__tests__/announcements.test.ts, src/api/__tests__/events.test.ts, src/api/__tests__/masquerade.test.ts, src/api/__tests__/persons.test.ts, src/api/__tests__/student.test.ts, src/api/admin.ts, src/api/alerts.ts, src/api/announcements.ts, src/api/events.ts, src/api/information.ts, src/api/persons.ts, src/api/resources.ts, src/api/student.ts, src/auth.ts
fixes https://jira.sig.oregonstate.edu/browse/DD-678
=> errors return json with consistent data shape

src/api/__mocks__/announcements.data.ts, src/api/__tests__/admin.test.ts, src/api/__tests__/alerts.test.ts, src/api/__tests__/announcements.test.ts, src/api/__tests__/events.test.ts, src/api/__tests__/masquerade.test.ts, src/api/__tests__/persons.test.ts, src/api/__tests__/student.test.ts, src/api/admin.ts, src/api/alerts.ts, src/api/announcements.ts, src/api/events.ts, src/api/information.ts, src/api/modules/dx.ts, src/api/persons.ts, src/api/resources.ts, src/api/student.ts, src/auth.ts, support/dxApi.http
fixes https://jira.sig.oregonstate.edu/browse/DD-639
=> Announcements filtering

.prettierrc, src/api/__mocks__/student.data.ts, src/api/modules/osu.ts, support/osuApi.http
fixes https://jira.sig.oregonstate.edu/browse/DD-709
=> fixing GPA level bugs

.vscode/launch.json, README.md, package.json, src/api/__tests__/user.test.ts, src/api/models/__tests__/user.test.ts, src/api/models/user.ts, src/api/user.ts, support/dxApi.http, yarn.lock
fixes https://jira.sig.oregonstate.edu/browse/DD-688
=> adds user settings persistence

src/api/__mocks__/resources.data.ts, src/api/__tests__/resources.test.ts, src/api/modules/dx.ts, src/api/resources.ts
We added a new data source in the backend api that needed to be exposed to the front-end application
=> Exposing Affiliation to the front-end for Resources

README.md, src/api/admin.ts, src/utils/__tests__/config.test.ts, src/utils/config.ts
=> Admin config api

config/default.ts, src/api/__tests__/events.test.ts, src/api/events.ts, src/api/modules/localist.ts, src/mocks/localist/events-employee.data.json, src/mocks/localist/events-employee.ts
Needs the front end as well after change.
=> Employee calendar

src/__tests__/auth.test.ts, src/api/__tests__/student.test.ts, src/api/__tests__/user.test.ts, src/api/models/__tests__/user.test.ts, src/api/models/user.ts, src/api/modules/user-account.ts, src/api/student.ts, src/api/user.ts, src/auth.ts, src/utils/mock-user.ts
fixes https://jira.sig.oregonstate.edu/browse/DD-743
=> adds grouper groups and masquerade improvements

src/api/models/__mocks__/user.ts, src/api/models/__tests__/user.test.ts, src/api/models/user.ts, src/api/modules/__tests__/canvas.test.ts, src/index.ts
fixes https://jira.sig.oregonstate.edu/browse/DD-780
will follow-up with a ticket to address the student-employee data from saml
=> redirects only students to canvas auth on first visit

.github/workflows/build_push_dev.yml, .github/workflows/build_push_prod.yml, .github/workflows/build_push_stage.yml, .github/workflows/workflow.yml, .npmrc, README.md, package.json, src/api/modules/dx.ts, src/api/modules/rave-alerts.ts, src/api/resources.ts, yarn.lock
updates project to start using shared library from @osu-wams/dx-monorepo/packages/lib 
merge before https://github.com/osu-wams/dx/pull/245
=> Lib package types

src/api/__tests__/announcements.test.ts, src/api/modules/dx.ts, src/mocks/dx/announcements-academics.data.expected.ts, src/mocks/dx/announcements-finances.data.expected.ts, src/mocks/dx/announcements.data.expected.ts, src/mocks/dx/announcements.data.json, support/dxApi.http
adds affiliation to announcement query
=> Announcement affiliation

src/api/models/__tests__/user.test.ts, src/api/models/user.ts
fixes https://jira.sig.oregonstate.edu/browse/DD-826
=> fixes bug with users who have no groups

package.json, src/api/modules/dx.ts, src/mocks/dx/categories.data.expected.ts, src/mocks/dx/categories.data.json, support/dxApi.http, yarn.lock
fixes https://jira.sig.oregonstate.edu/browse/DD-818
=> Categories affiliation

src/mocks/localist/events-corvallis.data.ts, src/mocks/localist/events-employee.data.ts, src/mocks/localist/events-employee.ts
USE_MOCKS flag was crashing due to the date formatting, this is a fix for that functionality and the tests
=> fixes event related mock data for display and test

__mocks__/redis.ts, config/default.ts, src/api/modules/cache.ts, src/api/modules/dx.ts, src/index.ts
fixes https://jira.sig.oregonstate.edu/browse/DD-831
remove explicit session save per this issue on GH: https://github.com/tj/connect-redis/issues/292
=> Resources long cache

src/utils/__tests__/resources.test.ts, src/utils/resources.ts
makes trending resource computation unique on resource, affiliation, and campus
=> Trending resources uniqueness

config/development.ts
Reverts osu-wams/dx-server#146 after load testing was complete
=> Revert "temporarily use mocks on development server for load testing with mocks"

package.json, src/api/__tests__/resources.test.ts, src/api/modules/dx.ts, src/mocks/dx/resources-academic.data.expected.ts, src/mocks/dx/resources-academic.data.json, src/mocks/dx/resources-featured-employee.data.json, src/mocks/dx/resources-featured.data.expected.ts, src/mocks/dx/resources-featured.data.json, src/mocks/dx/resources-financial.data.json, src/mocks/dx/resources.data.expected.ts, src/mocks/dx/resources.data.json, support/dxApi.http, yarn.lock
fixes https://jira.sig.oregonstate.edu/browse/DD-882
=> Trending exclusion

src/api/__tests__/releaseNotes.test.ts, src/api/modules/dx.ts, support/dxApi.http
fixes server side needs for https://jira.sig.oregonstate.edu/browse/DD-910
=> returns 6 most recent DX release notes

src/api/__tests__/user.test.ts, src/api/modules/__tests__/dx-mcm.test.ts, src/api/modules/dx-mcm.ts, src/api/user.ts
fixes backend for https://jira.sig.oregonstate.edu/browse/DD-857
=> Mcm message read

package.json, src/api/__tests__/events.test.ts, src/api/modules/localist.ts, yarn.lock
fixes https://jira.sig.oregonstate.edu/browse/DD-941
=> Campus code bugfix

src/auth.ts, src/constants.ts, src/index.ts, src/logger.ts
fixes https://jira.sig.oregonstate.edu/browse/DD-947
=> explicitly destroys session on logout

src/api/__tests__/student.test.ts, src/api/modules/osu.ts
fixes https://jira.sig.oregonstate.edu/browse/DD-948
=> returns no academic standing when the status does not include one

src/api/models/__mocks__/user.ts, src/api/models/__tests__/user.test.ts, src/api/models/user.ts, src/api/modules/user-account.ts, src/db/__mocks__/index.ts, src/utils/__tests__/auth.test.ts, src/utils/auth.ts
fixes https://jira.sig.oregonstate.edu/browse/DD-918
=> adds onid and login date to user record

src/index.ts
fixes https://jira.sig.oregonstate.edu/browse/DD-976
=> Session bugfix

package.json, src/api/index.ts, src/api/modules/dx.ts, src/api/trainings.ts, src/mocks/dx/index.ts, src/mocks/dx/trainings.data.expected.ts, src/mocks/dx/trainings.data.json, support/dxApi.http, yarn.lock
fixes https://jira.sig.oregonstate.edu/browse/DD-940
=> Employee trainings

.github/workflows/build_push_dev.yml, .github/workflows/build_push_prod.yml, .github/workflows/build_push_stage.yml
fixes https://jira.sig.oregonstate.edu/browse/DD-979 for server
=> adds deployment notification pre and post to slack channel

src/index.ts
fixes https://jira.sig.oregonstate.edu/browse/DD-904
=> extends cookie max age to 4hr

src/api/modules/dx.ts
=> fixes a silly bug in making the jsonapi query

package.json, src/api/modules/osu.ts, yarn.lock
fixes https://jira.sig.oregonstate.edu/browse/DD-965
=> uses gpalevel from lib package

src/mocks/dx-mcm/user-messages.data.json
updates mock data shape from MCM
=> updates mock data for updated mcm usermessage

src/logger.ts, src/mocks/dx-mcm/user-messages.data.json
fixes https://jira.sig.oregonstate.edu/browse/DD-1055
=> Cloud logging bugfix

config/default.ts
fixes https://jira.sig.oregonstate.edu/browse/DD-1073
=> reduces cache time for cachet

src/utils/__tests__/routing.test.ts, src/utils/routing.ts
https://jira.sig.oregonstate.edu/browse/DD-1180
=> fixed deeplinks bug

src/api/__mocks__/holds.data.ts, src/api/__tests__/student.test.ts, src/api/modules/osu.ts
- also added fromDate to hold data type
- modified tests to reflect new return value
=> added fromDate to student holds API

config/default.ts
=> Changed osuApi error thresholds

src/api/modules/dx.ts, support/dxApi.http
Adding a missing field to alerts api request from drupal
=> Missing revision timestamp

src/api/modules/__tests__/dx-mcm.test.ts
Ticket: https://oregonstateuniversity.atlassian.net/browse/DD-1370
=> Refactor dx mcm tests to use MSW handlers

src/api/modules/__tests__/ready-education.test.ts, src/mocks/apis.ts, src/mocks/handlers.ts
Ticket: https://oregonstateuniversity.atlassian.net/browse/DD-1376
=> Refactor ready education test to use msw

src/api/modules/__tests__/google.test.ts
Ticket: https://oregonstateuniversity.atlassian.net/browse/DD-1375
=> Refactor google tests to use msw

src/api/modules/__tests__/cache.test.ts, src/mocks/apis.ts, src/mocks/handlers.ts
Ticket: https://oregonstateuniversity.atlassian.net/browse/DD-1377
=> Refactor cache test to use MSW

src/api/modules/__tests__/cachet.test.ts
Ticket: https://oregonstateuniversity.atlassian.net/browse/DD-1378
=> Refactor cachet tests to use MSW handlers
